package io.github.kliushnichenko.jooby.mcp.apt.generator;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.palantir.javapoet.*;
import io.github.kliushnichenko.jooby.mcp.JoobyMcpServer;
import io.github.kliushnichenko.jooby.mcp.apt.McpServerDescriptor;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

public class McpServerGenerator {

    private static final String MCP_SERVER_CLASS_NAME = "McpServer";
    private final Filer filer;

    private static final List<McpFeature> FEATURES = List.of(
            new McpToolsFeature(),
            new McpPromptsFeature(),
            new McpCompletionsFeature(),
            new McpResourcesFeature()
    );

    public McpServerGenerator(Filer filer) {
        this.filer = filer;
    }

    public void generateMcpServers(List<McpServerDescriptor> serverDescriptors) throws IOException {
        for (McpServerDescriptor serverDescriptor : serverDescriptors) {
            generateMcpServer(serverDescriptor);
        }
    }

    private void generateMcpServer(McpServerDescriptor serverDescriptor) throws IOException {
        String className = capitalize(serverDescriptor.serverKey()) + MCP_SERVER_CLASS_NAME;

        TypeSpec.Builder mcpServerBuilder = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(ClassName.get(JoobyMcpServer.class))
                .addJavadoc("Generated Jooby MCP Server. Do not modify manually.");

        generateFields(mcpServerBuilder);
        generateInitMethod(mcpServerBuilder, serverDescriptor);
        generateInvokers(mcpServerBuilder);
        generateGetters(mcpServerBuilder, serverDescriptor.serverKey());

        writeJavaFile(mcpServerBuilder.build(), serverDescriptor.targetPackage());
    }

    void generateFields(TypeSpec.Builder builder) {
        FieldSpec joobyApp = FieldSpec.builder(
                        ClassName.get("io.jooby", "Jooby"),
                        "app",
                        Modifier.PRIVATE)
                .build();
        builder.addField(joobyApp);

        FEATURES.forEach(feature -> feature.generateFields(builder));
    }

    /**
     * Adds the init method to the server.
     * This method initializes the tools, prompts, resources and their invokers.
     */
    private void generateInitMethod(TypeSpec.Builder serverBuilder, McpServerDescriptor descriptor) {
        MethodSpec.Builder initMethodBuilder = MethodSpec.methodBuilder("init")
                .addModifiers(Modifier.PUBLIC)
                .addParameter(ClassName.get("io.jooby", "Jooby"), "app", Modifier.FINAL)
                .addParameter(ClassName.get(ObjectMapper.class), "objectMapper", Modifier.FINAL)
                .addJavadoc("Initialize a new server.")
                .addJavadoc("@param app the Jooby application instance")
                .addJavadoc("@param objectMapper json serializer instance");

        initMethodBuilder.addStatement("this.app = app");

        FEATURES.forEach(feature -> feature.generateInitializers(initMethodBuilder, descriptor));

        serverBuilder.addMethod(initMethodBuilder.build());
    }

    private void generateInvokers(TypeSpec.Builder builder) {
        FEATURES.forEach(feature -> feature.generateInvoker(builder));
    }

    private void generateGetters(TypeSpec.Builder builder, String serverKey) {
        FEATURES.forEach(feature -> feature.generateGetter(builder));

        MethodSpec getServerKeyMethod = MethodSpec.methodBuilder("getServerKey")
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", serverKey)
                .build();

        builder.addMethod(getServerKeyMethod);
    }

    private void writeJavaFile(TypeSpec serverClass, String targetPackage) throws IOException {
        JavaFile javaFile = JavaFile.builder(targetPackage, serverClass)
                .addFileComment("This file is generated by McpToolProcessor. Do not modify manually.")
                .build();

        javaFile.writeTo(filer);
    }

    private String capitalize(String str) {
        str = str.toLowerCase();
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }
} 